version: '3.1'

services:
  user-api:
    container_name: user-api
    build:
      context: .
      dockerfile: ./api/Dockerfile
    environment:
      ENVIRONMENT: local
      DB_ENDPOINT: mongodb://user-mongo/user-db
    ports:
      - 7701:7701
    depends_on:
      - mongodb
      - user-batch

  user-batch:
    container_name: user-batch
    build:
      context: .
      dockerfile: ./batch/Dockerfile
    volumes:
      - ./files:/files
    environment:
      FILE_CSV: /files/users.csv
      LIST_ONE: /files/lista_relevancia_1.txt
      LIST_TWO: /files/lista_relevancia_2.txt
    depends_on:
      - mongodb

  mongodb:
    container_name: user-mongo
    image: mongo:latest
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 7700:27017
    command: mongod --smallfiles --logpath=/dev/null

volumes:
  db-data: